angular.module('app.value')
.value('menus',[
    {
        "name":"trade",
        "url":"app.tradeMg",
        "subMenus":[
            {
                "name":"car",
                "url":"app.carMg"
            },{
                "name":"series",
                "url":"app.seriesMg"
            },{
                "name":"brand",
                "url":"app.brandMg"
            },
            {
                "name":"order",
                "url":"app.orderMg"
            }
        ]
    },
    {
        "name":"content",
        "url":"app.contentMg",
        "subMenus":[
            {
                "name":"news",
                "url":"app.newsMg"
            },
            {
                "name":"newsType",
                "url":"app.newsTypeMg"
            },
            {
                "name":"activity",
                "url":"app.activityMg"
            },
            {
                "name":"activityType",
                "url":"app.activityTypeMg"
            },
            {
                "name":"company",
                "url":"app.companyMg"
            }
        ]
    },
    {
        "name":"user",
        "url":"app.userMg",
        "subMenus":[
            {
                "name":"userList",
                "url":"app.userList"
            }
        ]
    },
    {
        "name":"staff",
        "url":"app.staffMg",
        "subMenus":[
            {
                "name":"staffList",
                "url":"app.staffMg.staffList"
            },
            {
                "name":"staffInfo",
                "url":"app.staffMg.staffInfoMg"
            }
        ]
    }
]
);
