angular.module('app.value')
.value('menus',[
    {
        "name":"trade",
        "url":"app.tradeMg",
        "subMenus":[
            {
                "name":"",
                "url":"",
                "subMenus":[
                    {
                        "name":"car",
                        "url":"app.tradeMg.carMg"
                    },{
                        "name":"series",
                        "url":"app.tradeMg.seriesMg"
                    },{
                        "name":"brand",
                        "url":"app.tradeMg.brandMg"
                    }
                ]
            },{
                "name":"",
                "url":"",
                "subMenus":[
                    {
                        "name":"order",
                        "url":"app.tradeMg.orderMg"
                    }
                ]
            }
        ]
    },
    {
        "name":"内容管理",
        "url":"app.contentMg",
        "subMenus":[
            {
                "name":"新闻管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"新闻列表管理",
                        "url":"app.contentMg.newsMg"
                    },
                    {
                        "name":"新闻类型管理",
                        "url":"app.contentMg.newsTypeMg"
                    }
                ]
            },
            {
                "name":"活动管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"活动列表管理",
                        "url":"app.contentMg.activityMg"
                    },
                    {
                        "name":"活动类型管理",
                        "url":"app.contentMg.activityTypeMg"
                    }
                ]
            },
            {
                "name":"展示厅管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"公司管理",
                        "url":"app.contentMg.companyMg"
                    }
                ]
            }
        ]
    },
    {
        "name":"用户管理",
        "url":"app.userMg",
        "subMenus":[
            {
                "name":"用户管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"用户列表",
                        "url":"app.userMg.userList"
                    }
                ]
            }
        ]
    }
]
);
